version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/crates"
    schedule:
      interval: "weekly"
    groups:
      rust-deps:
        patterns: ["*"]

  - package-ecosystem: "pub"
    directory: "/apps/wios_app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
